language: node_js
node_js:
  - "stable"
branches:
  only: 
    - master
    - dev 
notifications:
  email:
    recipients:
      - jgarriss@mitre.org
      - lmalinowski@mitre.org
      - jchenry@mitre.org
    on_success: always
    on_failure: never
jobs:
  include:
    - stage: "Tests"
    
    - name: "Linter"
      script: npm run lint

    - name: "Unit Tests"
      script: npm run test:unit
      
    - name: "Build" 
      # Run build in the test stage, since using a seperate stage
      # means if tests fail then the build cmd isnt even run
      script: npm run build
